using System.Text;

namespace Agentry.Generator.Emit;

/// <summary>
/// Turns an <see cref="AgentModel"/> into C#. Strings in, string out.
/// </summary>
/// <remarks>
/// <para>
/// No <c>Compilation</c>, no <c>ISymbol</c>, no <c>SemanticModel</c> reaches
/// this class, and that is enforced by it simply not being passed one. Emit is
/// where it is tempting to reach back for "just one more" piece of type
/// information, and doing so re-roots the compilation the model was built to
/// avoid holding.
/// </para>
/// <para>
/// Plain <see cref="StringBuilder"/> rather than the Roslyn syntax factories:
/// generated code is read by humans far more often than it is manipulated, and
/// a syntax tree built by hand is harder to read than the code it produces.
/// </para>
/// </remarks>
internal static class AgentEmitter
{
    public static string Emit(AgentModel model)
    {
        var code = new StringBuilder();

        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Generated by Agentry. Do not edit; edit the [Agent] interface instead.");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine();

        if (model.Namespace.Length > 0)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();
        }

        code.AppendLine("/// <summary>");
        code.Append("/// Generated implementation of <see cref=\"").Append(model.InterfaceName).AppendLine("\"/>.");
        code.AppendLine("/// </summary>");
        code.Append(model.Accessibility)
            .Append(" sealed partial class ").Append(model.ImplementationName)
            .Append(" : ").AppendLine(model.InterfaceName);
        code.AppendLine("{");

        // The prompt as a constant, which is the entire reason for the attribute
        // design: it survives compilation and trimming, and is greppable.
        code.Append("    private const string SystemPrompt = ").Append(Literal(model.SystemPrompt)).AppendLine(";");
        code.AppendLine();
        code.AppendLine("    private readonly global::Agentry.AgentRunner _runner;");
        code.AppendLine();
        code.Append("    public ").Append(model.ImplementationName)
            .AppendLine("(global::Agentry.AgentRunner runner) => _runner = runner;");

        EmitToolManifest(code, model);

        foreach (var method in model.Methods)
        {
            EmitMethod(code, method);
        }

        code.AppendLine("}");
        return code.ToString();
    }

    /// <summary>
    /// Emits what this agent may call, as data.
    /// </summary>
    /// <remarks>
    /// A static property rather than something built at construction: the
    /// manifest is a fact about the type, known at compile time, and there is
    /// no moment at run time when it could differ. Building it in a constructor
    /// would be doing work to arrive at a constant.
    /// <para>
    /// The schema is a verbatim literal. Nothing reflects over the tool method
    /// to produce it, which is what makes this survive trimming.
    /// </para>
    /// </remarks>
    private static void EmitToolManifest(StringBuilder code, AgentModel model)
    {
        code.AppendLine();
        code.AppendLine("    /// <summary>What this agent may call. Compile-time constant.</summary>");
        code.AppendLine("    public static global::Agentry.ToolManifest Tools { get; } = new(");
        code.AppendLine("        new global::Agentry.ToolDescriptor[]");
        code.AppendLine("        {");

        foreach (var tool in model.Tools)
        {
            code.AppendLine("            new(");
            code.Append("                ").Append(Literal(tool.Name)).AppendLine(",");
            code.Append("                ").Append(Literal(tool.Description)).AppendLine(",");
            code.Append("                ").Append(Literal(tool.ParametersSchema)).AppendLine(",");
            code.Append("                new string[] { ");

            var first = true;
            foreach (var permission in tool.Permissions)
            {
                if (!first) code.Append(", ");
                code.Append(Literal(permission));
                first = false;
            }

            code.AppendLine(" }),");
        }

        code.AppendLine("        });");
    }

    private static void EmitMethod(StringBuilder code, MethodModel method)
    {
        var ct = method.CancellationTokenParameter ?? "default";

        code.AppendLine();
        code.AppendLine("    /// <inheritdoc/>");
        // Types arrive already fully qualified from the model. Nothing here
        // prepends "global::" — see the note in AgentGenerator.ReadMethod.
        code.Append("    public async global::System.Threading.Tasks.Task<")
            .Append(method.ReturnType).Append("> ").Append(method.Name).Append('(');

        var first = true;
        foreach (var parameter in method.Parameters)
        {
            if (!first) code.Append(", ");
            code.Append(parameter.Type).Append(' ').Append(parameter.Name);
            first = false;
        }

        if (method.CancellationTokenParameter is { } token)
        {
            if (!first) code.Append(", ");
            code.Append("global::System.Threading.CancellationToken ").Append(token).Append(" = default");
        }

        code.AppendLine(")");
        code.AppendLine("    {");
        code.AppendLine("        var call = new global::Agentry.AgentCall");
        code.AppendLine("        {");
        code.AppendLine("            SystemPrompt = SystemPrompt,");
        code.Append("            TaskPrompt = ").Append(Literal(method.TaskPrompt)).AppendLine(",");
        code.Append("            Operation = ").Append(Literal(method.Name)).AppendLine(",");
        code.AppendLine("            Arguments = new global::System.Collections.Generic.KeyValuePair<string, string>[]");
        code.AppendLine("            {");

        foreach (var parameter in method.Parameters)
        {
            // A string argument goes in as-is; anything else is rendered by
            // generated code that knows its static type, so the runtime never
            // needs to ask what type it was.
            var rendered = parameter.IsString
                ? parameter.Name
                : $"global::System.Text.Json.JsonSerializer.Serialize({parameter.Name})";

            code.Append("                new(").Append(Literal(parameter.Name)).Append(", ")
                .Append(rendered).AppendLine("),");
        }

        code.AppendLine("            },");
        code.AppendLine("        };");
        code.AppendLine();

        if (method.Shape == ReturnShape.Text)
        {
            code.Append("        return await _runner.CompleteTextAsync(call, ").Append(ct)
                .AppendLine(").ConfigureAwait(false);");
        }
        else
        {
            code.AppendLine("#pragma warning disable IL2026, IL3050 // P1 binds JSON reflectively; see AgentRunner.");
            code.Append("        return await _runner.CompleteJsonAsync<").Append(method.ReturnType)
                .Append(">(call, null, ").Append(ct).AppendLine(").ConfigureAwait(false);");
            code.AppendLine("#pragma warning restore IL2026, IL3050");
        }

        code.AppendLine("    }");
    }

    /// <summary>
    /// A verbatim string literal, with quotes doubled.
    /// </summary>
    /// <remarks>
    /// Prompts are multi-line and full of punctuation, so verbatim is the only
    /// sane form. The one escape a verbatim literal needs is <c>""</c>, and
    /// getting this wrong produces generated code that does not compile — with
    /// the error reported against a file the user cannot open.
    /// </remarks>
    private static string Literal(string value) => "@\"" + value.Replace("\"", "\"\"") + "\"";
}
