using System.Linq;
using System.Text;

namespace Agentry.Generator.Emit;

/// <summary>
/// Turns an <see cref="AgentModel"/> into C#. Strings in, string out.
/// </summary>
/// <remarks>
/// <para>
/// No <c>Compilation</c>, no <c>ISymbol</c>, no <c>SemanticModel</c> reaches
/// this class, and that is enforced by it simply not being passed one. Emit is
/// where it is tempting to reach back for "just one more" piece of type
/// information, and doing so re-roots the compilation the model was built to
/// avoid holding.
/// </para>
/// <para>
/// Plain <see cref="StringBuilder"/> rather than the Roslyn syntax factories:
/// generated code is read by humans far more often than it is manipulated, and
/// a syntax tree built by hand is harder to read than the code it produces.
/// </para>
/// </remarks>
internal static class AgentEmitter
{
    public static string Emit(AgentModel model)
    {
        var code = new StringBuilder();

        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Generated by Agentry. Do not edit; edit the [Agent] interface instead.");

        // Where the prompt came from, for whoever opens this file wondering why
        // the constant below does not match the attribute they are looking at.
        if (model.PromptFile.Length > 0)
        {
            code.Append("// Prompt read at compile time from: ").AppendLine(model.PromptFile);
        }

        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine();

        if (model.Namespace.Length > 0)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();
        }

        code.AppendLine("/// <summary>");
        code.Append("/// Generated implementation of <see cref=\"").Append(model.InterfaceName).AppendLine("\"/>.");
        code.AppendLine("/// </summary>");
        code.Append(model.Accessibility)
            .Append(" sealed partial class ").Append(model.ImplementationName)
            .Append(" : ").AppendLine(model.InterfaceName);
        code.AppendLine("{");

        // The prompt as a constant, which is the entire reason for the attribute
        // design: it survives compilation and trimming, and is greppable.
        code.Append("    private const string SystemPrompt = ").Append(ToolEmit.Literal(model.SystemPrompt)).AppendLine(";");
        code.AppendLine();
        code.AppendLine("    private readonly global::Agentry.AgentRunner _runner;");

        if (model.Tools.Count > 0)
        {
            // Both are required rather than optional. An authorizer that
            // defaults to "allow" would make the safe path the one you have to
            // remember, which is the wrong way round for a permission gate.
            code.Append("    private readonly ").Append(model.ImplementationName)
                .AppendLine("Tools _tools;");
            code.AppendLine("    private readonly global::Agentry.IToolAuthorizer _authorizer;");
        }

        // Only when some method asks for a role. The common case stays one
        // dependency, and a router in a constructor is then a signal that this
        // agent genuinely spans models rather than boilerplate to skim past.
        var routed = model.Methods.Any(m => m.ModelRole is not null);
        if (routed)
        {
            code.AppendLine("    private readonly global::Agentry.IModelRouter _router;");
        }

        code.AppendLine();
        code.Append("    public ").Append(model.ImplementationName)
            .Append("(global::Agentry.AgentRunner runner");

        if (model.Tools.Count > 0)
        {
            code.Append(", ").Append(model.ImplementationName).Append("Tools tools")
                .Append(", global::Agentry.IToolAuthorizer authorizer");
        }

        if (routed)
        {
            code.Append(", global::Agentry.IModelRouter router");
        }

        code.AppendLine(")");
        code.AppendLine("    {");
        code.AppendLine("        _runner = runner;");

        if (model.Tools.Count > 0)
        {
            code.AppendLine("        _tools = tools;");
            code.AppendLine("        _authorizer = authorizer;");
        }

        if (routed)
        {
            code.AppendLine("        _router = router;");
        }

        code.AppendLine("    }");

        // Unconditional, even with no tools: present and empty rather than
        // absent, so a caller never has to ask whether this agent has a
        // manifest before reading it.
        ToolEmit.Manifest(code, "    ", model.Tools);

        foreach (var method in model.Methods)
        {
            EmitMethod(code, method, model.Tools.Count > 0);
        }

        code.AppendLine("}");

        if (model.Tools.Count > 0)
        {
            ToolEmit.Invoker(
                code,
                model.Accessibility,
                model.ImplementationName + "Tools",
                model.ToolsType,
                model.ImplementationName + ".Tools",
                model.Tools);
        }

        return code.ToString();
    }

    private static void EmitMethod(StringBuilder code, MethodModel method, bool hasTools)
    {
        var ct = method.CancellationTokenParameter ?? "default";

        code.AppendLine();
        code.AppendLine("    /// <inheritdoc/>");
        // Types arrive already fully qualified from the model. Nothing here
        // prepends "global::" — see the note in AgentGenerator.ReadMethod.
        code.Append("    public async global::System.Threading.Tasks.Task<")
            .Append(method.ReturnType).Append("> ").Append(method.Name).Append('(');

        var first = true;
        foreach (var parameter in method.Parameters)
        {
            if (!first) code.Append(", ");
            code.Append(parameter.Type).Append(' ').Append(parameter.Name);
            first = false;
        }

        if (method.CancellationTokenParameter is { } token)
        {
            if (!first) code.Append(", ");
            code.Append("global::System.Threading.CancellationToken ").Append(token).Append(" = default");
        }

        code.AppendLine(")");
        code.AppendLine("    {");
        code.AppendLine("        var call = new global::Agentry.AgentCall");
        code.AppendLine("        {");
        code.AppendLine("            SystemPrompt = SystemPrompt,");
        code.Append("            TaskPrompt = ").Append(ToolEmit.Literal(method.TaskPrompt)).AppendLine(",");
        code.Append("            Operation = ").Append(ToolEmit.Literal(method.Operation)).AppendLine(",");

        if (method.ReturnSchema.Length > 0)
        {
            // The shape the model must produce, as a literal. This is the other
            // half of "schemas at compile time" — parameters had one and return
            // types did not, so a model was told to reply with JSON and left to
            // guess which JSON.
            code.Append("            ResponseSchema = ").Append(ToolEmit.Literal(method.ReturnSchema)).AppendLine(",");
        }
        code.AppendLine("            Arguments = new global::System.Collections.Generic.KeyValuePair<string, string>[]");
        code.AppendLine("            {");

        foreach (var parameter in method.Parameters)
        {
            // A string argument goes in as-is; anything else is rendered by
            // generated code that knows its static type, so the runtime never
            // needs to ask what type it was.
            var rendered = parameter.IsString
                ? parameter.Name
                : $"global::System.Text.Json.JsonSerializer.Serialize({parameter.Name})";

            code.Append("                new(").Append(ToolEmit.Literal(parameter.Name)).Append(", ")
                .Append(rendered).AppendLine("),");
        }

        code.AppendLine("            },");
        code.AppendLine("        };");
        code.AppendLine();

        // An agent with tools uses them on every generation method. The
        // alternative — tools only on methods returning string — makes whether
        // a method can call a tool depend on its return type, which is a rule
        // nobody would guess.
        var tools = hasTools ? $", _tools, _authorizer, {method.MaxIterations}" : string.Empty;

        // Resolved per call rather than cached, so a router backed by scoped DI
        // behaves. Roles are a handful of registrations; the lookup is a
        // dictionary hit next to a model round trip.
        var runner = method.ModelRole is { } role
            ? $"_router.For({ToolEmit.Literal(role)})"
            : "_runner";

        if (method.Shape == ReturnShape.Text)
        {
            var name = hasTools ? "CompleteWithToolsAsync" : "CompleteTextAsync";
            code.Append("        return await ").Append(runner).Append('.').Append(name).Append("(call")
                .Append(tools).Append(", ").Append(ct).AppendLine(").ConfigureAwait(false);");
        }
        else
        {
            code.AppendLine("#pragma warning disable IL2026, IL3050 // P1 binds JSON reflectively; see AgentRunner.");

            if (hasTools)
            {
                code.Append("        return await ").Append(runner).Append(".CompleteJsonWithToolsAsync<").Append(method.ReturnType)
                    .Append(">(call").Append(tools).Append(", null, ").Append(ct)
                    .AppendLine(").ConfigureAwait(false);");
            }
            else
            {
                code.Append("        return await ").Append(runner).Append(".CompleteJsonAsync<").Append(method.ReturnType)
                    .Append(">(call, null, ").Append(ct).AppendLine(").ConfigureAwait(false);");
            }

            code.AppendLine("#pragma warning restore IL2026, IL3050");
        }

        code.AppendLine("    }");
    }
}
