using System.Linq;
using System.Text;

namespace AgentInfer.Generator.Emit;

/// <summary>
/// Turns an <see cref="AgentModel"/> into C#. Strings in, string out.
/// </summary>
/// <remarks>
/// <para>
/// No <c>Compilation</c>, no <c>ISymbol</c>, no <c>SemanticModel</c> reaches
/// this class, and that is enforced by it simply not being passed one. Emit is
/// where it is tempting to reach back for "just one more" piece of type
/// information, and doing so re-roots the compilation the model was built to
/// avoid holding.
/// </para>
/// <para>
/// Plain <see cref="StringBuilder"/> rather than the Roslyn syntax factories:
/// generated code is read by humans far more often than it is manipulated, and
/// a syntax tree built by hand is harder to read than the code it produces.
/// </para>
/// </remarks>
internal static class AgentEmitter
{
    public static string Emit(AgentModel model)
    {
        var code = new StringBuilder();

        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Generated by AgentInfer. Do not edit; edit the [Agent] interface instead.");

        // Where the prompt came from, for whoever opens this file wondering why
        // the constant below does not match the attribute they are looking at.
        if (model.PromptFile.Length > 0)
        {
            code.Append("// Prompt read at compile time from: ").AppendLine(model.PromptFile);
        }

        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using System.Collections.Generic;");
        code.AppendLine("using System.Threading;");
        code.AppendLine("using System.Threading.Tasks;");
        code.AppendLine();

        if (model.Namespace.Length > 0)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();
        }

        code.AppendLine("/// <summary>");
        code.Append("/// Generated implementation of <see cref=\"").Append(model.InterfaceName).AppendLine("\"/>.");
        code.AppendLine("/// </summary>");
        code.Append(model.Accessibility)
            .Append(" sealed partial class ").Append(model.ImplementationName)
            .Append(" : ").AppendLine(model.InterfaceName);
        code.AppendLine("{");

        // The prompt as a constant, which is the entire reason for the attribute
        // design: it survives compilation and trimming, and is greppable.
        code.Append("    private const string SystemPrompt = ").Append(ToolEmit.Literal(model.SystemPrompt)).AppendLine(";");
        code.AppendLine();
        code.AppendLine("    private readonly global::AgentInfer.AgentRunner _runner;");

        if (model.Tools.Count > 0)
        {
            // Both are required rather than optional. An authorizer that
            // defaults to "allow" would make the safe path the one you have to
            // remember, which is the wrong way round for a permission gate.
            code.Append("    private readonly ").Append(model.ImplementationName)
                .AppendLine("Tools _tools;");
            code.AppendLine("    private readonly global::AgentInfer.IToolAuthorizer _authorizer;");
        }

        // Only when some method asks for a role. The common case stays one
        // dependency, and a router in a constructor is then a signal that this
        // agent genuinely spans models rather than boilerplate to skim past.
        var routed = model.Methods.Any(m => m.ModelRole is not null);
        if (routed)
        {
            code.AppendLine("    private readonly global::AgentInfer.IModelRouter _router;");
        }

        code.AppendLine();
        code.Append("    public ").Append(model.ImplementationName)
            .Append("(global::AgentInfer.AgentRunner runner");

        if (model.Tools.Count > 0)
        {
            code.Append(", ").Append(model.ImplementationName).Append("Tools tools")
                .Append(", global::AgentInfer.IToolAuthorizer authorizer");
        }

        if (routed)
        {
            code.Append(", global::AgentInfer.IModelRouter router");
        }

        code.AppendLine(")");
        code.AppendLine("    {");
        code.AppendLine("        _runner = runner;");

        if (model.Tools.Count > 0)
        {
            code.AppendLine("        _tools = tools;");
            code.AppendLine("        _authorizer = authorizer;");
        }

        if (routed)
        {
            code.AppendLine("        _router = router;");
        }

        code.AppendLine("    }");

        // Unconditional, even with no tools: present and empty rather than
        // absent, so a caller never has to ask whether this agent has a
        // manifest before reading it.
        ToolEmit.Manifest(code, "    ", model.Tools);

        foreach (var method in model.Methods)
        {
            EmitMethod(code, method, model.Tools.Count > 0, model.JsonContext.Length > 0 && method.Shape == ReturnShape.Json);
        }

        code.AppendLine("}");

        if (model.JsonContext.Length > 0)
        {
            foreach (var method in model.Methods)
            {
                if (method.Shape == ReturnShape.Json) EmitContract(code, model, method);
            }
        }

        if (model.Tools.Count > 0)
        {
            ToolEmit.Invoker(
                code,
                model.Accessibility,
                model.ImplementationName + "Tools",
                model.ToolsType,
                model.ImplementationName + ".Tools",
                model.Tools);
        }

        return code.ToString();
    }

    /// <summary>
    /// Schema, binding metadata and value rule for one return type, as one class.
    /// </summary>
    /// <remarks>
    /// <para>
    /// All three come from one read of the return type and its attributes, so
    /// they cannot disagree — which is the failure this replaces. A model
    /// answered <c>score: 100</c> to a field meant to be 1–5 and bound cleanly,
    /// because the schema said "integer" and the check lived somewhere else.
    /// </para>
    /// <para>
    /// <c>TypeInfo</c> reaches into a <c>JsonSerializerContext</c> the consumer
    /// declared. It cannot be emitted here: generators do not chain, so a
    /// context written by this generator is invisible to System.Text.Json's and
    /// compiles to an abstract class with no metadata in it. Referencing one is
    /// fine — both generators' outputs land in the same compilation.
    /// </para>
    /// </remarks>
    private static void EmitContract(StringBuilder code, AgentModel model, MethodModel method)
    {
        var name = method.Name + "Contract";
        var element = method.ReturnType.Substring(method.ReturnType.LastIndexOf('.') + 1);

        code.AppendLine();
        code.AppendLine("/// <summary>What the model is told, how it is bound, and what it must satisfy.</summary>");
        code.Append("file sealed class ").Append(name)
            .Append(" : global::AgentInfer.IReplyContract<").Append(method.ReturnType).AppendLine(">");
        code.AppendLine("{");
        code.Append("    public static ").Append(name).AppendLine(" Instance { get; } = new();");
        code.AppendLine();
        code.Append("    public string Schema => ").Append(ToolEmit.Literal(method.ReturnSchema)).AppendLine(";");
        code.AppendLine();
        // Reached by type, not by the member name the other generator will
        // choose. That name is the simple type name for ordinary records and
        // something else entirely for generics and nested types, so guessing it
        // works until somebody returns a Task<Page<Row>>. AIN014 has already
        // checked the context declares this type, so the null branch is for a
        // context edited afterwards rather than the common case.
        code.Append("    private static readonly global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<")
            .Append(method.ReturnType).AppendLine("> Info =");
        code.Append("        (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<")
            .Append(method.ReturnType).Append(">?)").Append(model.JsonContext)
            .Append(".Default.GetTypeInfo(typeof(").Append(method.ReturnType).AppendLine("))");
        code.Append("        ?? throw new global::System.InvalidOperationException(")
            .Append(ToolEmit.Literal(
                $"{model.JsonContext} does not serialize {method.ReturnType}. Add [JsonSerializable(typeof({element}))] to it."))
            .AppendLine(");");
        code.AppendLine();
        code.Append("    public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<")
            .Append(method.ReturnType).AppendLine("> TypeInfo => Info;");
        code.AppendLine();
        code.Append("    public string? Validate(").Append(method.ReturnType).AppendLine(" value)");
        code.AppendLine("    {");

        foreach (var check in method.ReturnChecks)
        {
            code.Append("        ").AppendLine(check);
        }

        code.AppendLine("        return null;");
        code.AppendLine("    }");
        code.AppendLine("}");
    }

    private static void EmitMethod(StringBuilder code, MethodModel method, bool hasTools, bool hasContract)
    {
        var ct = method.CancellationTokenParameter ?? "default";

        code.AppendLine();
        code.AppendLine("    /// <inheritdoc/>");
        // Types arrive already fully qualified from the model. Nothing here
        // prepends "global::" — see the note in AgentGenerator.ReadMethod.
        code.Append("    public async global::System.Threading.Tasks.Task<")
            .Append(method.ReturnType).Append("> ").Append(method.Name).Append('(');

        var first = true;
        foreach (var parameter in method.Parameters)
        {
            if (!first) code.Append(", ");
            code.Append(parameter.Type).Append(' ').Append(parameter.Name);
            first = false;
        }

        if (method.CancellationTokenParameter is { } token)
        {
            if (!first) code.Append(", ");
            code.Append("global::System.Threading.CancellationToken ").Append(token).Append(" = default");
        }

        code.AppendLine(")");
        code.AppendLine("    {");
        code.AppendLine("        var call = new global::AgentInfer.AgentCall");
        code.AppendLine("        {");
        code.AppendLine("            SystemPrompt = SystemPrompt,");
        code.Append("            TaskPrompt = ").Append(ToolEmit.Literal(method.TaskPrompt)).AppendLine(",");
        code.Append("            Operation = ").Append(ToolEmit.Literal(method.Operation)).AppendLine(",");

        // Omitted when a contract carries it: the runtime refuses both, because
        // a schema in two places is one of them being out of date.
        if (method.ReturnSchema.Length > 0 && !hasContract)
        {
            // The shape the model must produce, as a literal. This is the other
            // half of "schemas at compile time" — parameters had one and return
            // types did not, so a model was told to reply with JSON and left to
            // guess which JSON.
            code.Append("            ResponseSchema = ").Append(ToolEmit.Literal(method.ReturnSchema)).AppendLine(",");
        }
        code.AppendLine("            Arguments = new global::System.Collections.Generic.KeyValuePair<string, string>[]");
        code.AppendLine("            {");

        foreach (var parameter in method.Parameters)
        {
            // A string argument goes in as-is; anything else is rendered by
            // generated code that knows its static type, so the runtime never
            // needs to ask what type it was.
            var rendered = parameter.IsString
                ? parameter.Name
                : $"global::System.Text.Json.JsonSerializer.Serialize({parameter.Name})";

            code.Append("                new(").Append(ToolEmit.Literal(parameter.Name)).Append(", ")
                .Append(rendered).AppendLine("),");
        }

        code.AppendLine("            },");
        code.AppendLine("        };");
        code.AppendLine();

        // An agent with tools uses them on every generation method. Restricting
        // them to methods returning string would make whether a method can call
        // a tool depend on its return type.
        var tools = hasTools ? $", _tools, _authorizer, {method.MaxIterations}" : string.Empty;

        // Resolved per call rather than cached, so a router backed by scoped DI
        // behaves. Roles are a handful of registrations; the lookup is a
        // dictionary hit next to a model round trip.
        var runner = method.ModelRole is { } role
            ? $"_router.For({ToolEmit.Literal(role)})"
            : "_runner";

        if (method.Shape == ReturnShape.Text)
        {
            var name = hasTools ? "CompleteWithToolsAsync" : "CompleteTextAsync";
            code.Append("        return await ").Append(runner).Append('.').Append(name).Append("(call")
                .Append(tools).Append(", ").Append(ct).AppendLine(").ConfigureAwait(false);");
        }
        else if (hasContract)
        {
            // No pragma: the contract carries a JsonTypeInfo from a
            // source-generated context and checks its own values, so there is no
            // reflection here for an analyzer to warn about.
            var contract = method.Name + "Contract.Instance";

            if (hasTools)
            {
                code.Append("        return await ").Append(runner).Append(".CompleteJsonWithToolsAsync(call, ")
                    .Append(contract).Append(tools).Append(", ").Append(ct)
                    .AppendLine(").ConfigureAwait(false);");
            }
            else
            {
                code.Append("        return await ").Append(runner).Append(".CompleteJsonAsync(call, ")
                    .Append(contract).Append(", ").Append(ct).AppendLine(").ConfigureAwait(false);");
            }
        }
        else
        {
            code.AppendLine("#pragma warning disable IL2026, IL3050 // Reflective bind; declare [assembly: AgentInferJson] to avoid.");

            if (hasTools)
            {
                code.Append("        return await ").Append(runner).Append(".CompleteJsonWithToolsReflectivelyAsync<").Append(method.ReturnType)
                    .Append(">(call").Append(tools).Append(", null, ").Append(ct)
                    .AppendLine(").ConfigureAwait(false);");
            }
            else
            {
                code.Append("        return await ").Append(runner).Append(".CompleteJsonReflectivelyAsync<").Append(method.ReturnType)
                    .Append(">(call, null, ").Append(ct).AppendLine(").ConfigureAwait(false);");
            }

            code.AppendLine("#pragma warning restore IL2026, IL3050");
        }

        code.AppendLine("    }");
    }
}
