using System.Linq;
using System.Text;

namespace AgentInfer.Generator.Emit;

/// <summary>
/// Emits the set of model roles this compilation actually uses.
/// </summary>
/// <remarks>
/// <para>
/// For validating registration, not for writing attributes. A generated
/// constant cannot be used in the attribute that produced it — the generator
/// reads the attribute to learn the role, so a constant derived from that role
/// is circular by construction. Define your own constants for the attribute
/// side; this is the other half, and it exists so registration can be checked
/// against the roles in use rather than against a list somebody maintains.
/// </para>
/// <para>
/// The point being: a role that no method asks for is dead configuration, and a
/// method asking for a role nothing registers is a crash on first call. Both
/// are visible at startup once the set is a compile-time constant.
/// </para>
/// </remarks>
internal static class RolesEmitter
{
    public static string Emit(string[] roles)
    {
        var code = new StringBuilder();

        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Generated by AgentInfer. Do not edit.");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("namespace AgentInfer;");
        code.AppendLine();
        code.AppendLine("/// <summary>The model roles this assembly's agents ask for.</summary>");
        code.AppendLine("/// <remarks>");
        code.AppendLine("/// Pass to <c>ValidateRoles</c> so a role nothing registers fails at");
        code.AppendLine("/// startup instead of on the first call that needs it.");
        code.AppendLine("/// </remarks>");
        code.AppendLine("internal static class AgentInferRoles");
        code.AppendLine("{");
        code.Append("    public static readonly string[] All = [");
        code.Append(string.Join(", ", roles.Select(role => "\"" + role.Replace("\"", "\\\"") + "\"")));
        code.AppendLine("];");
        code.AppendLine("}");

        return code.ToString();
    }
}
