using System.Text;

namespace AgentInfer.Generator.Emit;

/// <summary>
/// Turns a <see cref="ToolsModel"/> into an invoker, with no agent attached.
/// </summary>
/// <remarks>
/// The same manifest and the same dispatch switch an agent would have got —
/// <see cref="ToolEmit"/> writes both — minus the implementation class. What is
/// left is the part of generation that pays: schemas derived from parameter
/// types, permissions collected from attributes, and argument binding chosen
/// from static types. The part it drops is a prompt constant, a constructor and
/// one call site per method, which is pleasant to write by hand and does not
/// rot when a type changes.
/// </remarks>
internal static class ToolsEmitter
{
    public static string Emit(ToolsModel model)
    {
        var code = new StringBuilder();

        code.AppendLine("// <auto-generated/>");
        code.AppendLine("// Generated by AgentInfer. Do not edit; edit the [AgentTools] type instead.");
        code.AppendLine("#nullable enable");
        code.AppendLine();
        code.AppendLine("using System.Linq;");
        code.AppendLine();

        if (model.Namespace.Length > 0)
        {
            code.Append("namespace ").Append(model.Namespace).AppendLine(";").AppendLine();
        }

        ToolEmit.Invoker(
            code,
            model.Accessibility,
            model.InvokerName,
            model.ToolsType,
            "Tools",
            model.Tools);

        // Spliced into the class the call above just closed, so the manifest
        // sits on the invoker rather than on an agent. That is where it always
        // belonged: what a tool type offers is a fact about the tool type, and
        // hanging it off an agent meant two agents over one type described it
        // twice.
        var close = code.ToString().LastIndexOf('}');
        var body = new StringBuilder();
        ToolEmit.Manifest(body, "    ", model.Tools);

        return code.ToString(0, close) + body + "}\n";
    }
}
